### ISSUE TITLE
Error in Book 3 Chapter 3 Software Craftmanship, Part : Testing Form

### ISSUE THREAD

**Issue by anggieg** [realpython/support#164]
Hi, I have purchased your book, and follow along the coding process. However, when I reach the part (I mentioned in the title), I found an error when trying to run : python manage.py test payment  Here is the error : 

Creating test database for alias 'default'...
F..
======================================================================
FAIL: test_signin_form_data_validation_for_invalid_data (payment.tests.FormTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anggie/Projects/RealPython/django_ecommerce/django_ecommerce/payment/tests.py", line 49, in test_signin_form_data_validation_for_invalid_data
    invalid_data['error'][1], invalid_data["data"])
  File "/home/anggie/Projects/RealPython/django_ecommerce/django_ecommerce/payment/tests.py", line 29, in assertFormError
    self.assertEquals(test_form.errors[expected_error_name], expected_error_msg, msg="Expected {} : Actual {} : using data {}".format(test_form.errors[expected_error_name], expected_error_msg, pformat(data)))
AssertionError: Expected <ul class="errorlist"><li>This field is required.</li></ul> : Actual [u'This field is required'] : using data {'email': 'jj@email.com'}

----------------------------------------------------------------------
Ran 3 tests in 0.003s

FAILED (failures=1)
Destroying test database for alias 'default'...

I have tried to re-read the book and check and match every code, but I can't seem to find the cause. Please advise, so I can continue the course.

Thank You

**Comment by anggieg** [comment]
Hi, already Found the error, sorry. I forgot to type the dot "." after [u'This field is required']
