### ISSUE TITLE
Interacting with the web

### ISSUE THREAD

**Issue by WimAlsemgeest** [realpython/support#369]
Good day,

I am working on your course and until now it went smootly. But in the example on the chapter Interacting with the web there is a example getting the adres https://realpython.com/practice/aphrodite.html. 

When I try that example I get an error.
<code>
 => python webscrap1.py
Traceback (most recent call last):
  File "webscrap1.py", line 6, in <module>
    html_page = urlopen(my_adress)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
</code>

Then I try it on my own website, that did work. Why was it not working on the aphrodite.html site? what am I missing?

**Comment by dbader** [comment]
@WimAlsemgeest Thanks for the bug report—this is an issue with our new hosting infrastructure. Our CDN (CloudFlare) flags scrapers and bots and blocks them from accessing the site after a few tries. Unfortunately the course material references some pages hosted on realpython.com

We're working on a big update to the Real Python Course right now that should come out in the next few weeks that will revamp these exercises. So please stay tuned and thanks again for the report :)
